language: csharp
solution: TestTravis.sln
dist: trusty
addons:
  sonarcloud:
    organization: "travcsharp"
    token:
      secure: $SONAR_TOKEN 
    github_token:
      secure: $GITHUB_READ_REPO
install:
  - nuget restore TestTravis.sln
script:
  - xbuild /p:Configuration=Release TestTravis.sln
  - git fetch --unshallow --branch=master https://github.com/metagrobil/.NetTest.git metagrobil/.NetTest
  - sonar-scanner