language: csharp
solution: TestTravis.sln
dist: trusty
addons:
  sonarcloud:
    organization: "travcsharp"
    token:
      secure: $SONAR_TOKEN 
    github_token:
      secure: $GITHUB_READ_REPO
before_install:
 
# Only needed for submodules which we are not currently using.
# Replace the SSH URL with the public URL, then initialize submodules
# - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
# - git submodule update --init --recursive
  
# Run the build from org.eclipse.scanning
install:
 
# Set LD_LIBRARY_PATH for the tests. Also set a variable that attempts to clear /tmp on the travis node to avoid it getting large
env:
 
# compile and test
script: 
 