language: csharp
solution: TestTravis.sln
dist: trusty
install:
    - travis_retry nuget restore -source "https://www.nuget.org/api/v2" TestTravis.sln
script:
    - xbuild TestTravis.sln
    - sonar-scanner
addons:
  sonarcloud:
    organization: "travcsharp"
    token:
      secure: $SONAR_TOKEN 
    github_token:
      secure: $GITHUB_READ_REPO