language: csharp
solution: TestTravis.sln
dist: trusty
addons:
  sonarcloud:
    organization: "travcsharp"
    token:
      secure: $SONAR_TOKEN 
    github_token:
      secure: $GITHUB_READ_REPO
install:
  - nuget restore TestTravis.sln
script:
  - xbuild /p:Configuration=Release TestTravis.sln
  - git fetch --unshallow
  - mono ../tools/sonar/SonarQube.Scanner.MSBuild.exe begin /n:NGenerics /k:ngenerics-github /d:sonar.login=${SONAR_TOKEN} /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vstest.reportsPaths="*/TestResults/.trx" /v:"2.0"
  - dotnet build
  - dotnet test NGenerics.Tests --logger:trx
  - dotnet test NGenerics.Examples --logger:trx
  - mono ../tools/sonar/SonarQube.Scanner.MSBuild.exe end /d:sonar.login=${SONAR_TOKEN}