language: csharp
solution: TestTravis.sln
dist: trusty
addons:
  sonarcloud:
    organization: "travcsharp"
    token:
      secure: $SONAR_TOKEN 
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner