language: csharp
solution: TestTravis.sln
dist: trusty
mono: none
dotnet: 4.6.1
addons:
  sonarcloud:
    organization: "travcsharp"
    token:
      secure: $SONAR_TOKEN 
    github_token:
      secure: $GITHUB_READ_REPO
install:
  - nuget restore TestTravis.sln
script:
  - dotnet restore
  - xbuild /p:Configuration=Release TestTravis.sln