language: csharp
solution: TestTravis.sln
dist: trusty
token: SONAR_TOKEN
addons:
  sonarcloud:
    organization: "travcsharp"
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner