language: csharp
solution: TestTravis.sln
dist: trusty
addons:
  sonarcloud:
    organization: "travcsharp"
    token:
      secure: $SONAR_TOKEN 
    github_token:
      secure: $GITHUB_READ_REPO
install:
    travis_retry nuget restore -source "https://www.nuget.org/api/v2" Fibonacci.sln
script:
    xbuild TestTravis.sln
